### ISSUE TITLE
Code delimited slides with language hint are not rendered properly

### ISSUE THREAD

**Issue by jeantil** [gitpitch/gitpitch#128]
Trying to render a code delimited slide using a language hint yields the following error in the server logs: 
```
java.net.MalformedURLException: QueryString parameter should not have more than 2 = per part
```
The url syntax is indeed invalid : 
```
https://raw.githubusercontent.com/jeantil/gitpitch-125/126/md_backticked.md?lang=markdown?gp=25
```
notice the end of the url : 
```
md_backticked.md?lang=markdown?gp=25
```

complete server logs :
```
2017-11-09 08:54:26,502 Back-End-Pool [warn] c.g.s.WebService - download: failed pp=/github/jeantil/gitpitch-125/126 [ white, null ], from source=https://raw.githubusercontent.com/jeantil/gitpitch-125/126/md_backticked.md?lang=markdown?gp=25, ex={}
java.lang.RuntimeException: java.net.MalformedURLException: QueryString parameter should not have more than 2 = per part
    at play.libs.ws.ahc.AhcWSRequest.setQueryString(AhcWSRequest.java:106)
    at play.libs.ws.ahc.AhcWSRequest.<init>(AhcWSRequest.java:78)
    at play.libs.ws.ahc.AhcWSClient.url(AhcWSClient.java:38)
    at com.gitpitch.services.WebService.download(WebService.java:109)
    at com.gitpitch.services.WebService.fetchBytes(WebService.java:60)
    at com.gitpitch.services.DiskService.download(DiskService.java:155)
    at com.gitpitch.git.GRSService.download(GRSService.java:81)
    at com.gitpitch.services.CodeService.build(CodeService.java:82)
    at com.gitpitch.models.MarkdownModel.process(MarkdownModel.java:183)
    at com.gitpitch.models.MarkdownModel.lambda$new$0(MarkdownModel.java:111)
Caused by: java.net.MalformedURLException: QueryString parameter should not have more than 2 = per part
    at play.libs.ws.ahc.AhcWSRequest.setQueryString(AhcWSRequest.java:106)
    at play.libs.ws.ahc.AhcWSRequest.<init>(AhcWSRequest.java:78)
    at play.libs.ws.ahc.AhcWSClient.url(AhcWSClient.java:38)
    at com.gitpitch.services.WebService.download(WebService.java:109)
    at com.gitpitch.services.WebService.fetchBytes(WebService.java:60)
    at com.gitpitch.services.DiskService.download(DiskService.java:155)
    at com.gitpitch.git.GRSService.download(GRSService.java:81)
    at com.gitpitch.services.CodeService.build(CodeService.java:82)
    at com.gitpitch.models.MarkdownModel.process(MarkdownModel.java:183)
    at com.gitpitch.models.MarkdownModel.lambda$new$0(MarkdownModel.java:111)
```

actual presentation sample :  http://gitpitch.com/jeantil/gitpitch-125/126?grs=github&t=white#/4/2

**Comment by gitpitch** [comment]
It looks like you are using invalid code delimiter syntax. This is what I see in your `PITCHME.md` file:

```
+++?code=md_indented.md?lang=markdown
```

That is not valid URL param usage because you are using `?lang=` and not `&lang=`.

Can you update your code delimiter and try again?

**Comment by jeantil** [comment]
sorry about that, my mistake.
