### ISSUE TITLE
NullPointerException: scheme

### ISSUE THREAD

**Issue by cracker0dks** [gitpitch/gitpitch#152]
Hey, 
I'm running gitpitch on the latest docker image localy with:

`docker run -d --name gitpitch -e GP_GOGS_BASE=http://git.reutlingen-university.de -e GP_GITLAB_API=http://git.reutlingen-university.de/api/v1/ -e GP_GOGS_ACCESS_TOKEN=mykey -e GP_GOGS_AS_DEFAULT=true -p 9000:9000 knsit/gitpitch`

I try to access the public repo: http/localhost:9000/ksystem/testPitch/master
http://git.reutlingen-university.de/ksystem/testPitch/

But I get the error: 
```
2018-01-21 17:08:46,664 main [info] p.c.s.NettyServer - Listening for HTTP on /0.0.0.0:9000
2018-01-21 17:08:48,219 application-akka.actor.default-dispatcher-5 [debug] c.g.s.PitchService - cachedRepo: grmKey=GRM:/gogs/ksystem/testPitch
2018-01-21 17:08:48,226 Front-End-Pool [debug] c.g.s.PitchService - fetchRepo: pp=/gogs/ksystem/testPitch/master [ white, null ]
2018-01-21 17:08:48,226 Front-End-Pool [debug] c.g.s.GitService - fetchRepo: pp=/gogs/ksystem/testPitch/master [ white, null ]
2018-01-21 17:08:48,226 Front-End-Pool [debug] c.g.g.GRSManager - getService: matching Gogs
2018-01-21 17:08:48,226 Front-End-Pool [debug] c.g.g.GRSManager - getService: returning=com.gitpitch.git.vendors.Gogs@6bee7d61
2018-01-21 17:08:48,226 Front-End-Pool [debug] c.g.s.GitService - fetchRepo: apiCall=repos/ksystem/testPitch
2018-01-21 17:08:48,251 application-akka.actor.default-dispatcher-5 [error] application -

! @76l789097 - Internal server error, for (GET) [/ksystem/testPitch/master] ->

play.api.UnexpectedException: Unexpected exception[CompletionException: java.lang.NullPointerException: scheme]
        at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:289)
        at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:220)
        at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
        at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
        at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:100)
        at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:100)
        at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:99)
        at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
        at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
Caused by: java.util.concurrent.CompletionException: java.lang.NullPointerException: scheme
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException: scheme
        at org.asynchttpclient.util.Assertions.assertNotNull(Assertions.java:23)
        at org.asynchttpclient.uri.Uri.<init>(Uri.java:63)
        at org.asynchttpclient.uri.Uri.create(Uri.java:38)
        at org.asynchttpclient.uri.Uri.create(Uri.java:31)
        at org.asynchttpclient.RequestBuilderBase.setUrl(RequestBuilderBase.java:148)
        at play.libs.ws.ahc.AhcWSRequest.buildRequest(AhcWSRequest.java:461)
        at play.libs.ws.ahc.AhcWSRequest.lambda$execute$2(AhcWSRequest.java:426)
        at play.libs.ws.ahc.AhcWSRequest.execute(AhcWSRequest.java:429)
        at play.libs.ws.ahc.AhcWSRequest.execute(AhcWSRequest.java:419)
        at play.libs.ws.ahc.AhcWSRequest.get(AhcWSRequest.java:284)
```
Running gogs Version: 0.11.34.1122

is this an API problem? And why do I even need the api / apikey if the repo is public anyway?

Thanks for your help :)

**Comment by gitpitch** [comment]
> I'm running gitpitch on the latest docker image localy 

The latest docker image? Where did you get this image? It is not an officially supported image so I have no way of knowing if or how it works. You may want to contact whoever created the image for help.

 > And why do I even need the api / apikey if the repo is public anyway?

The GitPitch server can run with or without an API key. So the key is optional. Perhaps the docker image author has made the key mandatory for their image.

**Comment by cracker0dks** [comment]
Thanks for your answer. Sry, looked official. 
This is the link: https://hub.docker.com/r/knsit/gitpitch/

If the problem is not on your side, you can close this ticket. 
Thanks for help

**Comment by gitpitch** [comment]
No problem. Just fyi, you could verify 100% if the problem is with GitPitch or with the docker image by attempting to install the server locally using the [instructions provided](https://github.com/gitpitch/gitpitch/wiki/Server-Deploy-Instructions) on the Wiki. If a local install works then the problem is definitely related to the docker setup.

**Comment by gitpitch** [comment]
One quick idea you might want to try. The GP_GOGS_BASE flag on your `docker-run` command currently looks as follows:

```
GP_GOGS_BASE=http://git.reutlingen-university.de
```

I suggest you try the following:

```
GP_GOGS_BASE=http://git.reutlingen-university.de/
```

Note, I have appended a `/` to the end of the HTTP url. 

I don't know how this docker setup handles the flag but I do know that the GitPitch server requires the trailing slash in it's final runtime configuration. If you try this let me know how it goes.

**Comment by cracker0dks** [comment]
sadly not working with additional `/` as well. It seems, that I have to setup my own Docker Image. Thanks for your help.

**Comment by Ryuno-Ki** [comment]
@kns-it See above issue in your https://github.com/kns-it/Docker-GitPitch
